Fix aroma beta 17 incompatibilities, fix debug logger, bump version
PretendoNetwork/Inkay pull request #28
Opened 2024-05-07 08:54 UTC by TraceEntertains

Pretty self explanatory
Works fine on my wii u but will mark as a draft until confirmed working

2024-05-08 02:56 UTC, ashquarky commented
Code looks good to me, though you've got mixed tabs/spaces. Might want to see if whatever editor your using has an [EditorConfig](https://github.com/PretendoNetwork/Inkay/blob/main/.editorconfig) plugin.

2024-05-08 06:34 UTC, TraceEntertains commented
did a bunch of stuff but notifications still arent the way i wanted them to be, still a draft for now but i pushed all my latest changes so if anyone wants to take a look they can

2024-05-08 06:35 UTC, TraceEntertains commented
> Code looks good to me, though you've got mixed tabs/spaces. Might want to see if whatever editor your using has an [EditorConfig](https://github.com/PretendoNetwork/Inkay/blob/main/.editorconfig) plugin.

i do actually have multiple ides installed but i just use notepad++ because it starts quickly and is just files rather than folder/project based

2024-05-08 06:37 UTC, TraceEntertains commented
oh crap, the commit i put has debug defaulted to on (you can just comment out the "DEBUG := 1" line if you dont want debug but it will be commented before the pr is marked as ready for review)

2024-05-08 11:52 UTC, Maschell commented
I made PR for that PR: https://github.com/TraceEntertains/Inkay/pull/1

2024-05-08 17:26 UTC, Maschell requested changes

2024-05-08 17:26 UTC, Maschell commented on src/Notification.cpp
> +    auto err1 = NotificationModule_SetDefaultValue(NOTIFICATION_MODULE_NOTIFICATION_TYPE_ERROR,
Should be `NOTIFICATION_MODULE_NOTIFICATION_TYPE_INFO`, my bad

2024-05-08 19:20 UTC, TraceEntertains commented on src/Notification.cpp
> +    auto err1 = NotificationModule_SetDefaultValue(NOTIFICATION_MODULE_NOTIFICATION_TYPE_ERROR,
Fixed it

2024-05-08 19:24 UTC, TraceEntertains commented
[Inkay-pretendo.zip](https://github.com/PretendoNetwork/Inkay/files/15253804/Inkay-pretendo.zip)
Here's the plugin in a zip file (thanks github...) if anyone wants to test it

2024-05-08 22:43 UTC, FourHawk commented
Testing it and everything is working as expected, the message now shows up after boot and patching the wara wara plaza works now

2024-05-09 07:57 UTC, Ch3ck3rM0n commented
Using Aroma v19 with your release TraceEntertains and after a few reboots Mario Kart worked but for example with Splatoon I still get Error 101-0502. It seems not to be 100% compatible to me for the moment.

2024-05-09 10:13 UTC, FourHawk commented
Error code 101-0502 Normally just means that the server is overloaded, idk about 101-2210 however

2024-05-10 15:08 UTC, ItzSwirlz commented
It seems to be working for me on Aroma Beta 18, yesterday night I was able to play a Splatoon match.

2024-05-11 04:17 UTC, TraceEntertains commented
@jonbarrow PR generally seems to be working on Aroma Beta 17+, and its been sitting for a few days now, is it possible you could review this when you get the chance?

2024-05-12 02:15 UTC, ashquarky reviewed
Seems fine though I have a few question marks. Happy to merge after this though

2024-05-12 02:15 UTC, ashquarky commented on src/Notification.cpp
> +                                                   15.0f);
Does "SetDefaultValue" affect other plugins too? I've had a look at NotificationModule code and I'm not sure. https://github.com/wiiu-env/libnotifications/blob/75ce22a0f6f670f1fa9a55fb0780f650e6df6701/source/utils.cpp#L320
cc @Maschell

2024-05-12 02:15 UTC, ashquarky commented on src/config.cpp
> +}
I'm going to assume this is fine. As long as the previous config files are compatible we should be gucci.
(i.e. someone connected to Nintendo on the old plugin continues being connected to Nintendo after updating)

2024-05-12 02:15 UTC, ashquarky commented on src/main.cpp
> +    WHBLogUdpDeinit();
My understanding is that you're meant to use LogModule *or* the Cafe/UDP ones?
Also spacing but I'll fix that on merge

2024-05-12 06:25 UTC, Maschell commented on src/Notification.cpp
> +                                                   15.0f);
It does not

2024-05-12 17:16 UTC, TraceEntertains commented on src/main.cpp
> +    WHBLogUdpDeinit();
I'm honestly not sure tbh? I kinda just went by the example plugin for beta 17+ and don't really know what it's for, but it didn't seem to affect anything, so I'll remove it in the next commit

2024-05-12 17:27 UTC, Maschell commented on src/main.cpp
> +    WHBLogUdpDeinit();
> My understanding is that you're meant to use LogModule _or_ the Cafe/UDP ones? Also spacing but I'll fix that on merge

In my plugins I first try go init the logging module and if that fails it'll fallback to udp/cafe logging

2024-05-12 18:40 UTC, TraceEntertains commented on src/config.cpp
> +}
It should be fine, config save file formats are the same except the config int is now written as a bool (doesn't matter though as it treats ints and bools the same)

2024-05-13 00:36 UTC, ItzSwirlz approved these changes
Just tested with the latest commit and appears to be working fine for me - notification is showing, got 101-0502 (server overload which given Pretendo is a good sign the plugin works)

2024-05-13 05:44 UTC, ashquarky commented
Alright we'll call it good

2024-05-13 05:45 UTC, merged