Miiverse and Error applet patch
PretendoNetwork/Inkay pull request #5
Opened 2022-11-29 00:29 UTC by shutterbug2000

- Add non-NAND Miiverse patch
- Custom ban error, pulled from the Account server

Draft PR for now b/c I'd like it to be looked at a bit first :p

2022-11-29 01:26 UTC, ashquarky requested changes
Looking pretty good! I'm not sure about pulling in curl but if it's a feature that we want then I can deal with it. Few small cleanup changes

2022-11-29 01:26 UTC, ashquarky commented on Makefile
> +LIBS	:= -lwups -lmocha -lkernel -lsdutils -lcurl -lz -lmbedtls -lmbedcrypto -lmbedx509 -lwut
This build goes from 47K to 778K. I know why you've added curl but I do wonder if it's the best answer to the ban reason issue? Assuming we care about binary size, I've never gotten a straight answer from maschell as to how big the heap is other than "plenty"

2022-11-29 01:26 UTC, ashquarky commented on src/main.cpp
> +#include <sdutils/sdutils.h>
sdutils is seemingly unused?

2022-11-29 01:26 UTC, ashquarky commented on src/main.cpp
> +};
aren't these just strings? You're not changing the bit before the nulls

2022-11-29 01:26 UTC, ashquarky commented on src/main.cpp
> +uint32_t find(uint32_t start, uint32_t size, const char* original_val, size_t original_val_sz) {
Unused

2022-11-29 01:26 UTC, ashquarky commented on src/main.cpp
> +        //we do it when loading this file since it should only load once, preventing massive lag spikes as it searches all of MEM2 xD
I'm drafting a hopefully better way to handle mem2 searches, see the `devel` branch. fine to merge this for now until that's ready tho

2022-11-29 01:26 UTC, ashquarky commented on src/main.cpp
> +    if(strstr((char*)buffer, "# rootca.pem") && strstr((char*)buffer, "4CE7Y259RF06alPvERck/VSyWmxzViHJbC2XpEKzJ2EFIWNt6ii8TxpvQtyYq1XT")){
good find, wish I knew this was here when working on Martini

2022-11-29 01:38 UTC, ashquarky approved these changes

2023-03-22 22:22 UTC, ashquarky commented
I'm still kinda sad about linking libcurl, is it still possible to use the system curl lib in wut or did they scrub that? Pretendo already has lots of API endpoints set up for ancient TLS1.1-o-vision so that won't be an issue...

2023-03-23 02:43 UTC, ashquarky commented
Merged to a work branch for further improvements:
[ ] Using libcurlwrapper from Aroma
[ ] Fixing up Dockerfile/CI
[ ] Merge conflicts (I'm sure there's one I missed)

shutter, you should have push access, let me know.

2023-03-23 03:29 UTC, shutterbug2000 commented
@ashquarky See #9 c:

2023-03-23 03:29 UTC, closed without merging